name = "timetastic-weekly-report"
main = "weekly-reports.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["0 14 * * 5"] # Runs every Friday at 2:00 PM UTC 

# Add logging configuration
[logs]
worker_sample_rate = 1.0  # Sample 100% of requests 