name = "timetastic-weekly-report"
main = "weekly-reports.js"
compatibility_date = "2023-05-18"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["0 14 * * 5"] # Runs every Friday at 2:00 PM UTC 